web: su git -c 'bundle exec unicorn_rails -p ${PORT:="3000"} -E ${RAILS_ENV:="development"} -c ${UNICORN_CONFIG:="config/unicorn.rb"}'
worker: su git -c 'bundle exec sidekiq -q post_receive -q gitlab_shell'
sshd: /usr/sbin/sshd -D
