#!/bin/bash

cd ${APP_HOME}

if [ ! -f ".bootstrapped" ]; then
  chown -R git ${APP_HOME}
  su git -c "rsync -vax ${TMP_APP_HOME}/ ."
  su git -c "force=yes bundle exec rake gitlab:setup"
  su git -c "bundle exec rake assets:precompile"
  touch .bootstrapped
fi

foreman start
