---
secrets_file: ./.secrets.yml

userdata:
  email_from: ash@the-rebellion.net
  email_display_name: GitLab
  email_reply_to: ash@the-rebellion.net
  db_host: postgres
  db_name: gitlab
  db_username: gitlab

stacks:
- name: roro
  units:

  - name: base
    version: 1.0.0
    dockerfile: _base/Dockerfile
    startable: false

  - name: postfix
    version: 1.0.0
    dockerfile: postfix/Dockerfile
    # volumes:
    #   - /Users/ash/src/presentations/roro-perheron-aug-2015/app/code:/app
    needed_unit_names:
      - base

  - name: redis
    version: 1.0.0
    dockerfile: redis/Dockerfile
    # volumes:
    #   - /Users/ash/src/presentations/roro-perheron-aug-2015/app/code:/app
    needed_unit_names:
      - base

  - name: postgres
    version: 1.0.0
    dockerfile: postgres/Dockerfile
    # volumes:
    #   - /Users/ash/src/presentations/roro-perheron-aug-2015/app/code:/app
    needed_unit_names:
      - base

  - name: app
    version: 1.0.0
    dockerfile: app/Dockerfile
    # volumes:
    #   - /Users/ash/src/presentations/roro-perheron-aug-2015/app/code:/app
    ports:
      - '5000:5000'
    env:
      - DB_HOST="{{ userdata.db_host }}"
      - DB_NAME="{{ userdata.db_name }}"
      - DB_USERNAME="{{ userdata.db_username }}"
      - DB_PASSWORD="{{ secrets.db_password }}"
      - GITLAB_EMAIL_FROM="{{ userdata.email_from }}"
      - GITLAB_EMAIL_DISPLAY_NAME="{{ userdata.email_display_name }}"
      - GITLAB_EMAIL_REPLY_TO="{{ userdata.email_reply_to }}"

      # - RAILS_ENV="production"
      # - SERVER="puma"
    needed_unit_names:
      - base
      - postgres
      - redis
      - postfix
