base: &base
  adapter:  postgresql
  encoding: unicode
  host:     <%= ENV['POSTGRES_HOST'] %>
  port:     <%= ENV['POSTGRES_PORT'] %>
  database: <%= ENV['POSTGRES_NAME'] %>
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

production:
  <<: *base
  pool: 10

development:
  <<: *base
  pool: 5

staging:
  <<: *base
  pool: 5
