---
secrets_file: ./.secrets.yml

userdata:
  gitlab:
    shell_version: v2.6.4
    email_from: ash@the-rebellion.net
    email_display_name: GitLab
    email_reply_to: ash@the-rebellion.net
  redis_host: roro_redis
  db_host: roro_postgres
  db_name: gitlab
  db_username: gitlab

stacks:
- name: gliderlabs
  description: Gliderlabs goodness
  units:
    - name: resolvable
      version: 1.0.0
      docker_image: gliderlabs/resolvable:master
      restart_policy: always
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock
        - /etc/resolv.conf:/tmp/resolv.conf

- name: roro
  units:
  - name: base
    version: 1.0.0
    dockerfile: _base/Dockerfile
    startable: false

  - name: postfix
    version: 1.0.0
    dockerfile: postfix/Dockerfile
    # volumes:
    #   - /Users/ash/src/presentations/roro-perheron-aug-2015/app/code:/app
    needed_unit_names:
      - base
      # - gliderlabs:resolvable

  - name: redis
    version: 1.0.0
    dockerfile: redis/Dockerfile
    # volumes:
    #   - /Users/ash/src/presentations/roro-perheron-aug-2015/app/code:/app
    needed_unit_names:
      - base

  - name: postgres
    version: 1.0.0
    dockerfile: postgres/Dockerfile
    volumes:
      - /data/roro/postgres/data:/var/lib/postgresql/data
    needed_unit_names:
      - base
    env:
      - DB_NAME={{ userdata.db_name }}
      - DB_USERNAME={{ userdata.db_username }}
      - DB_PASSWORD={{ secrets.db_password }}

  - name: app
    version: 1.0.0
    dockerfile: app/Dockerfile
    # volumes:
    #   - /Users/ash/src/presentations/roro-perheron-aug-2015/app/code:/app
    ports:
      - '5000:5000'
    env:
      - RAILS_ENV=development
      - REDIST_HOST={{ userdata.redis_host }}
      - DB_HOST={{ userdata.db_host }}
      - DB_NAME={{ userdata.db_name }}
      - DB_USERNAME={{ userdata.db_username }}
      - DB_PASSWORD={{ secrets.db_password }}
      - GITLAB_SHELL_VERSION={{ userdata.gitlab.shell_version }}
      - GITLAB_EMAIL_FROM={{ userdata.gitlab.email_from }}
      - GITLAB_EMAIL_DISPLAY_NAME={{ userdata.gitlab.email_display_name }}
      - GITLAB_EMAIL_REPLY_TO={{ userdata.gitlab.email_reply_to }}
    needed_unit_names:
      - base
      - postgres
      - redis
      - postfix
