---
secrets_file: ./.secrets.yml

userdata:
  libgit_two_version: "0.22.2"
  gitlab:
    app_home: /app
    data_home: /data
    shell_version: v2.6.4
    email_from: ash@the-rebellion.net
    email_display_name: GitLab
    email_reply_to: ash@the-rebellion.net
  redis:
    host: roro_redis
    port: 6379
  postgres:
    host: roro_postgres
    port: 5432
    name: gitlab
    username: gitlab

stacks:
- name: gliderlabs
  description: Gliderlabs goodness
  units:
    - name: resolvable
      version: 1.0.0
      docker_image: gliderlabs/resolvable:master
      restart_policy: always
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock
        - /etc/resolv.conf:/tmp/resolv.conf

- name: roro
  units:
  - name: base
    version: 1.0.0
    dockerfile: _base/Dockerfile
    startable: false

  - name: postfix
    version: 1.0.0
    dockerfile: postfix/Dockerfile
    needed_unit_names:
      - base
      # - gliderlabs:resolvable

  - name: redis
    version: 1.0.0
    dockerfile: redis/Dockerfile
    env:
      - REDIS_PORT={{ userdata.redis.port }}
    needed_unit_names:
      - base

  - name: postgres
    version: 1.0.0
    dockerfile: postgres/Dockerfile
    volumes:
      - /data/roro/postgres/data:/var/lib/postgresql/data
    needed_unit_names:
      - base
    env:
      - POSTGRES_NAME={{ userdata.db_name }}
      - POSTGRES_USERNAME={{ userdata.postgres.username }}
      - POSTGRES_PASSWORD={{ secrets.postgres.password }}

  - name: gitlab
    version: 1.0.0
    dockerfile: gitlab/Dockerfile
    ports:
      - '5000:5000'
    env:
      - RAILS_ENV=development
      - REDIS_HOST={{ userdata.redis.host }}
      - REDIS_PORT={{ userdata.redis.port }}
      - POSTGRES_HOST={{ userdata.postgres.host }}
      - POSTGRES_PORT={{ userdata.postgres.port }}
      - POSTGRES_NAME={{ userdata.postgres.name }}
      - POSTGRES_USERNAME={{ userdata.postgres.username }}
      - POSTGRES_PASSWORD={{ secrets.postgres.password }}
      - GITLAB_APP_HOME={{ userdata.gitlab.app_home }}
      - GITLAB_DATA_HOME={{ userdata.gitlab.data_home }}
      - GITLAB_SHELL_VERSION={{ userdata.gitlab.shell_version }}
      - GITLAB_ROOT_PASSWORD={{ secrets.gitlab.root_password }}
      - GITLAB_EMAIL_FROM={{ userdata.gitlab.email_from }}
      - GITLAB_EMAIL_DISPLAY_NAME={{ userdata.gitlab.email_display_name }}
      - GITLAB_EMAIL_REPLY_TO={{ userdata.gitlab.email_reply_to }}
    needed_unit_names:
      - base
      - postgres
      - redis
      - postfix
