---
secrets_file: ./.secrets.yml

userdata:
  libgit_two_version: "0.22.2"
  rails:
    env: production
  gitlab:
    version: 7.14.0
    host: gitlab.192.168.99.100.xip.io
    port: 5000
    app_home: /app
    data_home: /data
    shell_version: v2.6.4
    email_from: ash@the-rebellion.net
    email_display_name: GitLab
    email_reply_to: ash@the-rebellion.net
  redis:
    host: infra_redis
    port: 6379
  postgres:
    host: infra_postgres
    port: 5432
    name: gitlab
    username: gitlab

project:
  name: percheron-gitlab
  description: A full GitLab stack using Percheron

stacks:
- name: gliderlabs
  description: Gliderlabs goodness
  units:
    - name: resolvable
      version: 1.0.0
      docker_image: gliderlabs/resolvable:master
      restart_policy: always
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock
        - /etc/resolv.conf:/tmp/resolv.conf

- name: common
  description: Common images to build upon
  units:
    - name: base
      version: 1.0.0
      dockerfile: _base/Dockerfile
      startable: false

- name: infra
  description: Infrastructure based units
  units:
    - name: postfix
      version: 1.0.0
      dockerfile: infra/postfix/Dockerfile
      #needed_unit_names:
        #- gliderlabs:resolvable

    - name: redis
      version: 1.0.0
      dockerfile: infra/redis/Dockerfile
      #needed_unit_names:
        #- gliderlabs:resolvable
      env:
        - REDIS_PORT={{ userdata.redis.port }}

    - name: postgres
      version: 1.0.0
      dockerfile: infra/postgres/Dockerfile
      volumes:
        - /data/roro/postgres/data:/var/lib/postgresql/data
      #needed_unit_names:
        #- gliderlabs:resolvable
      env:
        - POSTGRES_NAME={{ userdata.postgres.name }}
        - POSTGRES_USERNAME={{ userdata.postgres.username }}
        - POSTGRES_PASSWORD={{ secrets.postgres.password }}

- name: gitlab
  description: Open Source Git hosting platform
  units:
    - name: base
      version: 1.0.0
      dockerfile: gitlab/_base/Dockerfile
      startable: false
      #needed_unit_names:
        #- common:base

    - name: app
      version: 1.0.0
      dockerfile: gitlab/app/Dockerfile
      ports:
        - '5000:5000'
        - '2222:22'
      volumes:
        - /data/roro/gitlab/app:/app
      env:
        - SERVICE_NAME=app
        - SERVICE_TAGS=gitlab
        - PORT={{ userdata.gitlab.port }}
        - RAILS_ENV={{ userdata.rails.env }}
        - RAILS_SECRET_KEY_BASE={{ secrets.rails.secret_key_base }}
        - REDIS_HOST={{ userdata.redis.host }}
        - REDIS_PORT={{ userdata.redis.port }}
        - POSTGRES_HOST={{ userdata.postgres.host }}
        - POSTGRES_PORT={{ userdata.postgres.port }}
        - POSTGRES_NAME={{ userdata.postgres.name }}
        - POSTGRES_USERNAME={{ userdata.postgres.username }}
        - POSTGRES_PASSWORD={{ secrets.postgres.password }}
        - GITLAB_HOST={{ userdata.gitlab.host }}
        - GITLAB_PORT={{ userdata.gitlab.port }}
        - GITLAB_APP_HOME={{ userdata.gitlab.app_home }}
        - GITLAB_DATA_HOME={{ userdata.gitlab.data_home }}
        - GITLAB_SHELL_VERSION={{ userdata.gitlab.shell_version }}
        - GITLAB_ROOT_PASSWORD={{ secrets.gitlab.root_password }}
        - GITLAB_EMAIL_FROM={{ userdata.gitlab.email_from }}
        - GITLAB_EMAIL_DISPLAY_NAME={{ userdata.gitlab.email_display_name }}
        - GITLAB_EMAIL_REPLY_TO={{ userdata.gitlab.email_reply_to }}
      needed_unit_names:
        #- gliderlabs:resolvable
        - base
        #- infra:postgres
        #- infra:redis
        #- infra:postfix
