#!/bin/bash

if [ -z "$(ls -A "$PGDATA")" ]; then
  chown -R postgres:postgres ${PGBASE}

  su postgres -c 'initdb'
  sed -ri "s/^#(listen_addresses\s*=\s*)\S+/\1'*'/" "${PGDATA}"/postgresql.conf

  echo "CREATE DATABASE ${POSTGRES_NAME};" | su postgres -c 'postgres --single -jE'
  echo "CREATE USER ${POSTGRES_USERNAME} WITH SUPERUSER PASSWORD '${POSTGRES_PASSWORD}';" | su postgres -c 'postgres --single -jE'

  echo "host all all 0.0.0.0/0 md5" >> ${PGDATA}/pg_hba.conf
fi

su postgres -c 'postgres'
