base: &base
  adapter:  postgresql
  encoding: unicode
  host:     <POSTGRES_HOST>
  port:     <POSTGRES_PORT>
  database: <POSTGRES_NAME>
  username: <POSTGRES_USERNAME>
  password: <POSTGRES_PASSWORD>

production:
  <<: *base
  pool: 10

development:
  <<: *base
  pool: 5

staging:
  <<: *base
  pool: 5
